In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
records = [f for f in os.listdir() if 'records.xlsx' in f]
columns = ['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'STL', 'BLK', 'TOV', 'PF', 'PTS', 'PLUS_MINUS','TEAM_NAME_中文']
col_on =['SEASON_ID','GAME_ID','GAME_DATE','MIN']
columns_away = col_on+[col+'_Away' for col in columns if col not in col_on]
columns2 = ['jcTotalScore','总分', '大小分', '比赛双方']
columns_opp = {
    #作为主队时，OPP的数据是FGM_Away
    'host':['TEAM_NAME_中文_Away','FGM_Away','FG3M_Away','PTS_Away','AST_Away','OREB_Away'],
    #作为客队时，OPP的数据是FGM
    'away':['TEAM_NAME_中文','FGM','FG3M','PTS','AST','OREB'],
    #新的df的OPP相关列名
    'colname':['球队_OPP','FGM_OPP','FG3M_OPP','PTS_OPP','AST_OPP','OREB_OPP']
}

In [3]:
for f in records:
    print(f)
    df_new = pd.DataFrame()
    df = pd.read_excel(f)
    teams = df['hostTeamName'].unique()
    for team in teams:
        df_host = df[df['TEAM_NAME_中文']==team]
        df_away = df[df['TEAM_NAME_中文_Away']==team]
        #values_host指作为主队时的扩展数据，values_away指作为客队时的扩展数据
        values_host = np.concatenate([df_host[columns+columns2].values,df_host[columns_opp['host']].values],axis=1)
        values_away = np.concatenate([df_away[columns_away+columns2].values,df_away[columns_opp['away']].values],axis=1)
        df_team = pd.DataFrame(np.concatenate([values_host,values_away]),columns = columns+columns2+columns_opp['colname'])
        df_new = pd.concat([df_new,df_team])
    df_new.to_excel(f.split('.')[0]+'-team_games.xlsx',index=False)
df_new.head()

2005-06-records.xlsx
2006-07-records.xlsx
2007-08-records.xlsx
2008-09-records.xlsx
2009-10-records.xlsx
2010-11-records.xlsx
2011-12-records.xlsx
2012-13-records.xlsx
2013-14-records.xlsx
2014-15-records.xlsx
2015-16-records.xlsx
2016-17-records.xlsx

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,jcTotalScore,总分,大小分,比赛双方,球队_OPP,FGM_OPP,FG3M_OPP,PTS_OPP,AST_OPP,OREB_OPP
0,22016,1610612755,PHI,Philadelphia 76ers,21600011,2016-10-26,PHI vs. OKC,L,240,36,...,208.5,200,小,76人 vs. 雷霆,雷霆,39,6,103,19,13
1,22016,1610612755,PHI,Philadelphia 76ers,21600026,2016-10-29,PHI vs. ATL,L,240,28,...,201.5,176,小,76人 vs. 老鹰,老鹰,42,5,104,31,6
2,22016,1610612755,PHI,Philadelphia 76ers,21600046,2016-11-01,PHI vs. ORL,L,240,40,...,197.5,204,大,76人 vs. 魔术,魔术,42,6,103,29,12
3,22016,1610612755,PHI,Philadelphia 76ers,21600080,2016-11-05,PHI vs. CLE,L,240,40,...,205.5,203,小,76人 vs. 骑士,骑士,37,14,102,23,11
4,22016,1610612755,PHI,Philadelphia 76ers,21600093,2016-11-07,PHI vs. UTA,L,240,31,...,192.5,193,大,76人 vs. 爵士,爵士,43,11,109,20,10